INSERT INTO PAIS
(ID, NOMBRE)
VALUES(0, 'chile');

INSERT INTO GENERO
(ID, NOMBRE)
VALUES(0, 'terror');

INSERT INTO IDIOMA
(ID, NOMBRE)
VALUES(0, 'ingles');

INSERT INTO PAIS
(ID, NOMBRE)
VALUES(1, 'argentina');

INSERT INTO GENERO
(ID, NOMBRE)
VALUES(1, 'ficcion');

INSERT INTO IDIOMA
(ID, NOMBRE)
VALUES(0, 'ingles');


INSERT INTO PELICULA
(ID, TITULO, TITULODISTRIBUCION, AÑO, DURACION, URL, RESUMEN, GENERO_ID, PAIS_ID, IDIOMA_ID, SUBTITULADO)
VALUES(0, 'mas de 10', 'mas de 10', '2016', '160', 'www.google.cl', 'pelicula', 0, 0, 0, '1');

INSERT INTO PELICULA
(ID, TITULO, TITULODISTRIBUCION, AÑO, DURACION, URL, RESUMEN, GENERO_ID, PAIS_ID, IDIOMA_ID, SUBTITULADO)
VALUES(0, 'otra mas', 'otra mas', '2014', '160', 'www.google.cl', 'pelicula', 0, 1, 0, '1');


SELECT ID,PAIS.NOMBRE AS ORIGEN , IDIOMA.NOMBRE AS IDIOMA
FROM PELICULA INNER JOIN PAIS ON PAIS.ID=PELICULA.PAIS_ID 
INNER JOIN IDIOMA  PELICULA.IDIOMA_ID  = IDIOMA.ID 